/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.login;

import static com.raven.form.Form_Anggota.table;
import com.raven.main.Main;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import koneksi.config;

/**
 *
 * @author Legion
 */
public class LoginTab extends javax.swing.JPanel {
private Form_Login login;

    /**
     * Creates new form NewJPanel
     */
    public LoginTab() {
        initComponents();
        setOpaque(false);        
        
    }

    public JFrame login(){
        
        return login.main_f;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_user = new textfield.TextField();
        txt_pass = new textfield.PasswordField();
        btn_masuk = new com.k33ptoo.components.KButton();
        atau = new javax.swing.JLabel();
        masuk = new javax.swing.JLabel();
        daftar = new javax.swing.JLabel();
        btn_daftar = new com.k33ptoo.components.KButton();
        forget_pass = new javax.swing.JLabel();
        remember = new javax.swing.JLabel();

        txt_user.setBackground(new java.awt.Color(58, 71, 90));
        txt_user.setForeground(new java.awt.Color(255, 255, 255));
        txt_user.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_user.setLabelText("Username");
        txt_user.setLineColor(new java.awt.Color(107, 141, 160));
        txt_user.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txt_user.setSelectionColor(new java.awt.Color(0, 120, 215));
        txt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userActionPerformed(evt);
            }
        });

        txt_pass.setBackground(new java.awt.Color(56, 67, 87));
        txt_pass.setForeground(new java.awt.Color(255, 255, 255));
        txt_pass.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_pass.setLabelText("Password");
        txt_pass.setLineColor(new java.awt.Color(107, 141, 160));
        txt_pass.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txt_pass.setSelectionColor(new java.awt.Color(0, 120, 215));
        txt_pass.setShowAndHide(true);
        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passActionPerformed(evt);
            }
        });
        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passKeyPressed(evt);
            }
        });

        btn_masuk.setText("Masuk");
        btn_masuk.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btn_masuk.setkBorderRadius(40);
        btn_masuk.setkEndColor(new java.awt.Color(82, 207, 243));
        btn_masuk.setkHoverEndColor(new java.awt.Color(82, 207, 243));
        btn_masuk.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_masuk.setkHoverStartColor(new java.awt.Color(139, 223, 247));
        btn_masuk.setkPressedColor(new java.awt.Color(92, 148, 164));
        btn_masuk.setkStartColor(new java.awt.Color(40, 195, 239));
        btn_masuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_masukMouseClicked(evt);
            }
        });

        atau.setFont(new java.awt.Font("Helvetica Light", 1, 12)); // NOI18N
        atau.setForeground(new java.awt.Color(255, 255, 255));
        atau.setText("Atau");

        masuk.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        masuk.setForeground(new java.awt.Color(255, 255, 255));
        masuk.setText("Masuk");

        daftar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        daftar.setForeground(new java.awt.Color(204, 204, 204));
        daftar.setText("Daftar");
        daftar.setDoubleBuffered(true);
        daftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftarMouseClicked(evt);
            }
        });

        btn_daftar.setText("Daftar");
        btn_daftar.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btn_daftar.setkBorderRadius(40);
        btn_daftar.setkEndColor(new java.awt.Color(82, 207, 243));
        btn_daftar.setkHoverEndColor(new java.awt.Color(82, 207, 243));
        btn_daftar.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_daftar.setkHoverStartColor(new java.awt.Color(139, 223, 247));
        btn_daftar.setkPressedColor(new java.awt.Color(92, 148, 164));
        btn_daftar.setkStartColor(new java.awt.Color(40, 195, 239));
        btn_daftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_daftarMouseClicked(evt);
            }
        });

        forget_pass.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        forget_pass.setForeground(new java.awt.Color(113, 183, 204));
        forget_pass.setText("Lupa password?");
        forget_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forget_passMouseClicked(evt);
            }
        });

        remember.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        remember.setForeground(new java.awt.Color(113, 183, 204));
        remember.setText("Biarkan tetap masuk");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_daftar, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(masuk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(daftar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(remember)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(forget_pass))
                            .addComponent(txt_pass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(atau)
                        .addGap(119, 119, 119)))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masuk)
                    .addComponent(daftar))
                .addGap(54, 54, 54)
                .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forget_pass)
                    .addComponent(remember))
                .addGap(52, 52, 52)
                .addComponent(btn_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(atau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_daftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passActionPerformed

    private void txt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userActionPerformed

    private void daftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarMouseClicked
        
        Form_Login.panel.setSelectedIndex(1);
        
    }//GEN-LAST:event_daftarMouseClicked

    private void btn_daftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_daftarMouseClicked
        Form_Login.panel.setSelectedIndex(1);
    }//GEN-LAST:event_btn_daftarMouseClicked

    private void forget_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forget_passMouseClicked
        Form_Login.panel.setSelectedIndex(2);
    }//GEN-LAST:event_forget_passMouseClicked

    private void btn_masukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_masukMouseClicked
        try {
            login = new Form_Login();
            
            String sql = "SELECT * FROM register WHERE id='"+txt_user.getText()
                    +"'AND password='"+txt_pass.getText()+"'";
            Connection conn=(Connection)config.connectDB();
            PreparedStatement p = conn.prepareStatement(sql);                                   
            ResultSet rs = p.executeQuery(sql);
            if(rs.next()){
                if(txt_user.getText().equals(rs.getString("id"))
                    && Arrays.equals(txt_pass.getPassword(), (rs.getString("password")).toCharArray())) {
                    JOptionPane.showMessageDialog(this, "Berhasil Login");
                    
                    
                    new Main().setVisible(true);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Wrong Username or Password","Error Mesage", 
       JOptionPane.ERROR_MESSAGE);          }
            
            config.closeDB();
            rs.close();
            p.close();
        } catch (Exception e) {
            e.printStackTrace();
        }     
    }//GEN-LAST:event_btn_masukMouseClicked

    private void txt_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            
        
        try {
            
            String sql = "SELECT * FROM register WHERE id='"+txt_user.getText()
                    +"'AND password='"+txt_pass.getText()+"'";
            Connection conn=(Connection)config.connectDB();
            PreparedStatement p = conn.prepareStatement(sql);
                          
            login = new Form_Login();
            ResultSet rs = p.executeQuery(sql);
            if(rs.next()){
                if(txt_user.getText().equals(rs.getString("id"))
                    && Arrays.equals(txt_pass.getPassword(), (rs.getString("password")).toCharArray())) {
                    JOptionPane.showMessageDialog(this, "Berhasil Login");
                    setVisible(false);
                    login.dispose();
                    
                    
                    new Main().setVisible(true);
                    
                    
                }
            }else{
                JOptionPane.showMessageDialog(this, "Wrong Username or Password","Error Mesage", 
       JOptionPane.ERROR_MESSAGE);          }
            
            config.closeDB();
            rs.close();
            p.close();
        } catch (Exception e) {
            e.printStackTrace();
        }     
        }
    }//GEN-LAST:event_txt_passKeyPressed
    @Override
    protected void paintChildren(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, Color.decode("#3E4D61"), 0, getHeight(), Color.decode("#2D3144"));
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 0, 0);
        g2.fillRect(0, 0, getWidth(), getHeight());
        super.paintChildren(grphcs);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atau;
    private com.k33ptoo.components.KButton btn_daftar;
    private com.k33ptoo.components.KButton btn_masuk;
    public static javax.swing.JLabel daftar;
    private javax.swing.JLabel forget_pass;
    public static javax.swing.JLabel masuk;
    private javax.swing.JLabel remember;
    private textfield.PasswordField txt_pass;
    private textfield.TextField txt_user;
    // End of variables declaration//GEN-END:variables
}
