/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.login;

import com.raven.login.*;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author Legion
 */
public class RegisterTab extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public RegisterTab() {
        initComponents();
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_user = new textfield.TextField();
        passwordField1 = new textfield.PasswordField();
        masuk = new javax.swing.JLabel();
        daftar = new javax.swing.JLabel();
        btn_daftar = new com.k33ptoo.components.KButton();
        pertanyaan = new combobox.Combobox();
        jawaban = new textfield.TextField();

        txt_user.setBackground(new java.awt.Color(58, 71, 90));
        txt_user.setForeground(new java.awt.Color(255, 255, 255));
        txt_user.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_user.setLabelText("Username");
        txt_user.setLineColor(new java.awt.Color(107, 141, 160));
        txt_user.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txt_user.setSelectionColor(new java.awt.Color(0, 120, 215));
        txt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userActionPerformed(evt);
            }
        });

        passwordField1.setBackground(new java.awt.Color(56, 67, 87));
        passwordField1.setForeground(new java.awt.Color(255, 255, 255));
        passwordField1.setCaretColor(new java.awt.Color(255, 255, 255));
        passwordField1.setDisabledTextColor(new java.awt.Color(110, 144, 164));
        passwordField1.setLabelText("Password");
        passwordField1.setLineColor(new java.awt.Color(107, 141, 160));
        passwordField1.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        passwordField1.setSelectionColor(new java.awt.Color(0, 120, 215));
        passwordField1.setShowAndHide(true);
        passwordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordField1ActionPerformed(evt);
            }
        });

        masuk.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        masuk.setForeground(new java.awt.Color(204, 204, 204));
        masuk.setText("Masuk");
        masuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masukMouseClicked(evt);
            }
        });

        daftar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        daftar.setForeground(new java.awt.Color(255, 255, 255));
        daftar.setText("Daftar");
        daftar.setDoubleBuffered(true);

        btn_daftar.setText("Daftar");
        btn_daftar.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btn_daftar.setkBorderRadius(40);
        btn_daftar.setkEndColor(new java.awt.Color(82, 207, 243));
        btn_daftar.setkHoverEndColor(new java.awt.Color(82, 207, 243));
        btn_daftar.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_daftar.setkHoverStartColor(new java.awt.Color(139, 223, 247));
        btn_daftar.setkPressedColor(new java.awt.Color(92, 148, 164));
        btn_daftar.setkStartColor(new java.awt.Color(40, 195, 239));

        pertanyaan.setBackground(new java.awt.Color(54, 63, 83));
        pertanyaan.setForeground(new java.awt.Color(255, 255, 255));
        pertanyaan.setLabeText("Pertanyaan");
        pertanyaan.setLineColor(new java.awt.Color(107, 141, 160));

        jawaban.setBackground(new java.awt.Color(52, 60, 79));
        jawaban.setForeground(new java.awt.Color(255, 255, 255));
        jawaban.setCaretColor(new java.awt.Color(255, 255, 255));
        jawaban.setLabelText("Jawaban");
        jawaban.setLineColor(new java.awt.Color(107, 141, 160));
        jawaban.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jawaban.setSelectionColor(new java.awt.Color(0, 120, 215));
        jawaban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jawabanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pertanyaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_daftar, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addComponent(txt_user, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(masuk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(daftar))
                    .addComponent(passwordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addComponent(jawaban, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masuk)
                    .addComponent(daftar))
                .addGap(54, 54, 54)
                .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(passwordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(pertanyaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jawaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btn_daftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void passwordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordField1ActionPerformed

    private void txt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userActionPerformed

    private void masukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masukMouseClicked
        Form_Login.panel.setSelectedIndex(0);
    }//GEN-LAST:event_masukMouseClicked

    private void jawabanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jawabanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jawabanActionPerformed
    @Override
    protected void paintChildren(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, Color.decode("#3E4D61"), 0, getHeight(), Color.decode("#2D3144"));
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 0, 0);
        g2.fillRect(0, 0, getWidth(), getHeight());
        super.paintChildren(grphcs);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btn_daftar;
    private javax.swing.JLabel daftar;
    private textfield.TextField jawaban;
    private javax.swing.JLabel masuk;
    private textfield.PasswordField passwordField1;
    private combobox.Combobox pertanyaan;
    private textfield.TextField txt_user;
    // End of variables declaration//GEN-END:variables
}
